In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving students.csv to students.csv

In [ ]:
import pandas as pd

df = pd.read_csv("students.csv")
df.head()

      Name  Age       City  Marks
0    Alice   20  Hyderabad     85
1      Bob   21    Chennai     90
2  Charlie   19  Bangalore     78
3    David   22     Mumbai     88
4      Eva   20      Delhi     92

In [ ]:
df.head()

      Name  Age       City  Marks
0    Alice   20  Hyderabad     85
1      Bob   21    Chennai     90
2  Charlie   19  Bangalore     78
3    David   22     Mumbai     88
4      Eva   20      Delhi     92

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   City    5 non-null      object
 3   Marks   5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

In [ ]:
df.shape

(5, 4)

In [ ]:
df.columns

Index(['Name', 'Age', 'City', 'Marks'], dtype='object')

In [ ]:
df.describe()

             Age      Marks
count   5.000000   5.000000
mean   20.400000  86.600000
std     1.140175   5.458938
min    19.000000  78.000000
25%    20.000000  85.000000
50%    20.000000  88.000000
75%    21.000000  90.000000
max    22.000000  92.000000

In [ ]:
df.isnull().sum()

Name     0
Age      0
City     0
Marks    0
dtype: int64

In [ ]:
df["Marks"].mean()

np.float64(86.6)

In [ ]:
df[df["Marks"] > 80]

    Name  Age       City  Marks
0  Alice   20  Hyderabad     85
1    Bob   21    Chennai     90
3  David   22     Mumbai     88
4    Eva   20      Delhi     92

In [ ]:
df.sort_values("Marks", ascending=False)

      Name  Age       City  Marks
4      Eva   20      Delhi     92
1      Bob   21    Chennai     90
3    David   22     Mumbai     88
0    Alice   20  Hyderabad     85
2  Charlie   19  Bangalore     78

In [ ]:
df.to_csv("cleaned_students.csv", index=False)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df = df.drop_duplicates()

In [ ]:
df["Marks"].mean()

np.float64(86.6)

In [ ]:
df["Marks"].max()

92

In [ ]:
df["Marks"].min()

78

In [ ]:
df["Marks"].median()

88.0

In [ ]:
df[df["Marks"] > 80]

    Name  Age       City  Marks
0  Alice   20  Hyderabad     85
1    Bob   21    Chennai     90
3  David   22     Mumbai     88
4    Eva   20      Delhi     92

In [ ]:
df[df["Age"] > 20]

    Name  Age     City  Marks
1    Bob   21  Chennai     90
3  David   22   Mumbai     88

In [ ]:
df.sort_values(by="Marks", ascending=False)

      Name  Age       City  Marks
4      Eva   20      Delhi     92
1      Bob   21    Chennai     90
3    David   22     Mumbai     88
0    Alice   20  Hyderabad     85
2  Charlie   19  Bangalore     78

In [ ]:
import numpy as np

df["Result"] = np.where(df["Marks"] >= 40, "Pass", "Fail")

In [ ]:
df.head()

      Name  Age       City  Marks Result
0    Alice   20  Hyderabad     85   Pass
1      Bob   21    Chennai     90   Pass
2  Charlie   19  Bangalore     78   Pass
3    David   22     Mumbai     88   Pass
4      Eva   20      Delhi     92   Pass

In [ ]:
df.to_csv("cleaned_students.csv", index=False)

In [ ]:
from google.colab import files
files.download("cleaned_students.csv")